import type { DelegatedItem, InboxItem, Loop } from './types'

const now = Date.now()
const mins = (n: number) => now - n * 60_000
const hours = (n: number) => now - n * 3_600_000
const days = (n: number) => now - n * 86_400_000

export const seedLoops: Loop[] = [
  {
    id: 'l_1',
    title: 'Finalize Q2 OKRs draft',
    note: 'Aligning with leadership sync Thursday. Needs impact metrics from data team.',
    status: 'in_progress',
    priority: 'now',
    energy: 'deep',
    impact: 3,
    source: 'notion',
    createdAt: days(2),
    dueAt: hours(30),
    today: true,
    tags: ['strategy', 'leadership'],
  },
  {
    id: 'l_2',
    title: 'Reply to investor update thread',
    note: 'Three questions on runway, hiring plan, and competitive pressure.',
    status: 'open',
    priority: 'now',
    energy: 'shallow',
    impact: 3,
    source: 'email',
    createdAt: hours(4),
    today: true,
    tags: ['investors'],
    blockedBy: 'Data from finance',
  },
  {
    id: 'l_3',
    title: 'Follow up with Jamie re: contract redlines',
    status: 'waiting',
    priority: 'now',
    energy: 'shallow',
    impact: 2,
    source: 'slack',
    createdAt: days(1),
    today: true,
    blockedBy: 'Jamie (legal)',
  },
  {
    id: 'l_4',
    title: 'Outline keynote for all-hands',
    note: 'Theme: what breaks when we 3x. Lean on customer stories.',
    status: 'open',
    priority: 'soon',
    energy: 'deep',
    impact: 3,
    source: 'capture',
    createdAt: days(3),
    dueAt: days(-4), // 4 days from now
    tags: ['writing'],
  },
  {
    id: 'l_5',
    title: 'Review design system rollout plan',
    status: 'open',
    priority: 'soon',
    energy: 'deep',
    impact: 2,
    source: 'notion',
    createdAt: days(5),
    tags: ['design'],
  },
  {
    id: 'l_6',
    title: 'Decide on analytics vendor migration',
    note: 'Mixpanel vs. Amplitude vs. stay. Need to answer Ana by Friday.',
    status: 'open',
    priority: 'soon',
    energy: 'shallow',
    impact: 2,
    source: 'capture',
    createdAt: days(4),
    dueAt: days(-2),
    tags: ['decision'],
  },
  {
    id: 'l_7',
    title: 'Book flights for Atlanta conference',
    status: 'open',
    priority: 'later',
    energy: 'admin',
    impact: 1,
    source: 'calendar',
    createdAt: days(6),
  },
  {
    id: 'l_8',
    title: 'Reconcile last trip expenses',
    status: 'open',
    priority: 'later',
    energy: 'admin',
    impact: 1,
    source: 'email',
    createdAt: days(8),
  },
  {
    id: 'l_9',
    title: 'Draft blog post: "how we killed standups"',
    note: 'Rough outline saved in Notion. Voice memo has the opener.',
    status: 'in_progress',
    priority: 'soon',
    energy: 'deep',
    impact: 2,
    source: 'voice',
    createdAt: days(1),
    tags: ['writing'],
  },
  {
    id: 'l_10',
    title: 'Sketch onboarding redesign hypothesis',
    status: 'open',
    priority: 'later',
    energy: 'deep',
    impact: 3,
    source: 'capture',
    createdAt: days(10),
    tags: ['design', 'growth'],
  },
]

export const seedInbox: InboxItem[] = [
  {
    id: 'i_1',
    kind: 'email',
    source: 'email',
    from: 'Sarah Chen',
    preview: 'Revised pricing proposal attached — let me know if tier 2 works for your team.',
    receivedAt: mins(35),
    signal: 'high',
    actionable: true,
  },
  {
    id: 'i_2',
    kind: 'dm',
    source: 'slack',
    from: 'Alex Rivera',
    preview: 'quick q about the roadmap — is Q3 mobile still locked in?',
    receivedAt: mins(58),
    signal: 'high',
    actionable: true,
  },
  {
    id: 'i_3',
    kind: 'email',
    source: 'email',
    from: 'Board chair',
    preview: 'Can we sync Friday before the board meeting? 30 min.',
    receivedAt: hours(2),
    signal: 'high',
    actionable: true,
  },
  {
    id: 'i_4',
    kind: 'mention',
    source: 'slack',
    from: '#eng',
    preview: 'PR #142 review requested — design system tokens.',
    receivedAt: hours(3),
    signal: 'medium',
    actionable: true,
  },
  {
    id: 'i_5',
    kind: 'thread',
    source: 'slack',
    from: '#random',
    preview: '15 new messages about the offsite memes.',
    receivedAt: hours(4),
    signal: 'noise',
    thread: 15,
  },
  {
    id: 'i_6',
    kind: 'newsletter',
    source: 'email',
    from: 'LinkedIn',
    preview: '12 new connections, 3 posts from your network.',
    receivedAt: hours(6),
    signal: 'noise',
  },
  {
    id: 'i_7',
    kind: 'invite',
    source: 'calendar',
    from: 'Product review',
    preview: 'Tuesday 2pm — overlaps with your 1:1 with Morgan.',
    receivedAt: hours(8),
    signal: 'medium',
    actionable: true,
  },
  {
    id: 'i_8',
    kind: 'email',
    source: 'email',
    from: 'Stripe',
    preview: 'Your monthly invoice is ready.',
    receivedAt: hours(10),
    signal: 'noise',
  },
]

export const seedDelegated: DelegatedItem[] = [
  {
    id: 'd_1',
    title: 'Response to Sarah — pricing questions',
    summary: 'Drafted reply addressing tier 2 seat count and annual discount. Waiting on your approval.',
    state: 'drafted',
    source: 'email',
    to: 'Sarah Chen',
    updatedAt: mins(12),
  },
  {
    id: 'd_2',
    title: 'Decline 3 speaking requests',
    summary: 'Polite decline queued for conferences that don\'t match this quarter\'s theme.',
    state: 'scheduled',
    source: 'email',
    to: '3 recipients',
    updatedAt: mins(45),
  },
  {
    id: 'd_3',
    title: 'Summarize #product-updates (past week)',
    summary: '4 threads distilled to 6 bullets. Top signal: mobile parity complaint from 2 enterprise accounts.',
    state: 'sent',
    source: 'slack',
    to: 'you',
    updatedAt: hours(1),
  },
  {
    id: 'd_4',
    title: 'Calendar conflict on Tuesday 2pm',
    summary: 'Proposed three alternative times to Morgan. Awaiting reply.',
    state: 'awaiting_reply',
    source: 'calendar',
    to: 'Morgan',
    updatedAt: hours(2),
  },
]
